export interface GeoCodeData {
    name: string;
    local_names?: LocalNames | null;
    lat: number;
    lon: number;
    country: string;
    state?: string | null;
  }

export interface LocalNames {
  ur: string;
  bo?: string | null;
  sk?: string | null;
  he?: string | null;
  mn?: string | null;
  eo?: string | null;
  it?: string | null;
  cv?: string | null;
  hu: string;
  ga?: string | null;
  pl?: string | null;
  mk?: string | null;
  es: string;
  tg?: string | null;
  ka?: string | null;
  sl?: string | null;
  hr?: string | null;
  os?: string | null;
  cs?: string | null;
  bg?: string | null;
  az?: string | null;
  uk: string;
  ko: string;
  ht?: string | null;
  zh?: string | null;
  la?: string | null;
  tt?: string | null;
  ro: string;
  kv?: string | null;
  yi?: string | null;
  ug?: string | null;
  is?: string | null;
  fa?: string | null;
  af?: string | null;
  li?: string | null;
  tr?: string | null;
  ps?: string | null;
  bs?: string | null;
  fr?: string | null;
  av?: string | null;
  sr: string;
  oc?: string | null;
  th?: string | null;
  sh?: string | null;
  ku?: string | null;
  ca?: string | null;
  mr?: string | null;
  sq?: string | null;
  sv?: string | null;
  ar: string;
  gr: string;
  lt: string;
  kk?: string | null;
  en: string;
  be: string;
  ta?: string | null;
  ja?: string | null;
  ml?: string | null;
  de: string;
  gu?: string | null;
  my?: string | null;
  fy?: string | null;
  kn?: string | null;
  el: string;
  hy: string;
  uz?: string | null;
  ru: string;
  hi?: string | null;
  nl: string;
  pt?: string | null;
  bn?: string | null;
  am?: string | null;
  lv?: string | null;
  no?: string | null;
}
  